rootProject.name = 'pay'
include 'module-core'
include 'module-core:domain-core'
findProject(':module-core:domain-core')?.name = 'domain-core'
include 'module-core:rdbms-core'
findProject(':module-core:rdbms-core')?.name = 'rdbms-core'
include 'module-external-api'
include 'module-internal-api'
include 'module-adaptor'
include 'module-client'
include 'module-client:toss-payments-client'
findProject(':module-client:toss-payments-client')?.name = 'toss-payments-client'
include 'module-core:domain-core:payment-domain-core'
findProject(':module-core:domain-core:payment-domain-core')?.name = 'payment-domain-core'
include 'module-core:domain-core:payment-confirm-domain-core'
findProject(':module-core:domain-core:payment-confirm-domain-core')?.name = 'payment-confirm-domain-core'

