rootProject.name = 'product'
include 'module-common'
include 'module-external-api'
include 'module-internal-api'
include 'module-core'
include 'module-core:product-domain-core'
include 'module-core:product-rdbms-core'

findProject(':module-core:product-domain-core')?.name = 'product-domain-core'
findProject(':module-core:product-rdbms-core')?.name = 'product-rdbms-core'