rootProject.name = 'Member'
include 'module-core'
include 'module-internal-api'
include 'module-external-api'
include 'module-event-consumer'
include 'module-event-producer'
include 'module-common'

include 'module-core:member-domain-core'
findProject(':module-core:member-domain-core')?.name = 'member-domain-core'
include 'module-core:member-rdbms-core'
findProject(':module-core:member-rdbms-core')?.name = 'member-rdbms-core'

